# Generated by Django 2.2.3 on 2019-07-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0002_topic_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
