# Generated by Django 2.2.3 on 2019-07-24 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divisions', '0003_complain_is_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='is_pending',
        ),
        migrations.AddField(
            model_name='complain',
            name='resolve',
            field=models.ManyToManyField(blank=True, related_name='resolve', to=settings.AUTH_USER_MODEL),
        ),
    ]
